version: "3.8"

services:
  db:
    image: postgres:13
    hostname: cards_lookup_db
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
      - ./server/database_resources/compose_postgres_init.sh:/docker-entrypoint-initdb.d/compose-postgres-init.sh

  db_init:
    build:
      context: .
      dockerfile: Dockerfile_db_init
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_HOST: cards_lookup_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: cards_usr
      POSTGRES_DB: cards
    depends_on:
      - db

  webapp:
    build:
      context: .
      dockerfile: Dockerfile_webapp
    ports:
      - "3001:3001"
    depends_on:
      - db
      - db_init

volumes:
  postgres_data:
